---
meta:
  name: vault-credhub-proxy
  target: pipes@main
  url:     https://pipes.starkandwayne.com
  git:
    name: "CI Bot"
    email: "ci@starkandwayne.com"
  github:
    owner: starkandwayne
    repo:  vault-credhub-proxy
    private_key:  ((github.private-key))
    access_token: ((github.access-token))
  aws:
    access_key: ((cfcommunity.access))
    secret_key: ((cfcommunity.secret))
  slack:
    webhook: ((webhook))
    channel: "#nochannel"
